### ISSUE TITLE
`_fetch_site` doesn't respect the `JUJU_CHARMS_*_PROXY` environment variables

### ISSUE THREAD

**Issue by addyess** [jnsgruk/hello-kubecon#9]
https://github.com/jnsgruk/hello-kubecon/blob/master/src/charm.py#L100-L110

`urlretrieve` method fails when the charm is deployed behind a proxy

**Comment by jnsgruk** [comment]
Hey! Yeh indeed, this is a demo charm and isn't going to be upgraded to support such cases.
